# Generated by Django 5.2.6 on 2025-10-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('class_section', models.CharField(max_length=50)),
                ('exam_name', models.CharField(max_length=100)),
                ('subject_group', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=50)),
                ('student_status', models.CharField(max_length=50)),
                ('completion_percent', models.IntegerField(default=0)),
            ],
        ),
    ]
